const BRAND_COLORS = {
	BLUE: '#4F6BD5',
	DARK_PERIWINKLE: '#565CD4',
	DARK_BLUE: '#2D3D9A',
	DARK_PURPLE: '#4140AC',
	PURPLE: '#7261D0',
	LIGHT_PURPLE: '#8565CD',
	BRIGHT_PURPLE: '#8F3EE0',
	HIGHLIGHT_BLUE: '#EFF0F8',
}

const GREY_SCALE = {
	BLACK: '#000000',
	DARK_DETAIL_GREY: '#CCCCCC',
	LIGHT_GREY: '#E5E6EB',
	HOVER_GREY: '#F3F3F3',
	BACKGROUND_GREY: '#F8F9FA',
	WHITE: '#FFFFFF',
}

const OTHER_COLORS = {
	ERROR_RED: '#E44847',
	AFFIRMATION_GREEN: '#67CB99',
	DARK_MONEY_GREEN: '#0DAF5E',
	BRIGHT_YELLOW: '#FFD600',
	BRIGHT_PINK: '#EA4BBD',
	BRIGHT_BLUE: '#20A0E9',
}

const TEXT_COLORS = {
	SUB_TEXT_GREY: '#A8AFBB',
	INACTIVE: '#828792',
	DEFAULT: '#464646',
}

/**
 * Should not be needed in most cases, as usage will brake theming.
 * If you find a case where css vars cannot be used, then use this object.
 */
export const DESIGN_SYSTEM_COLORS = {
	BRAND_COLORS,
	GREY_SCALE,
	OTHER_COLORS,
	TEXT_COLORS,
	PRIMARY: BRAND_COLORS.BLUE,
	SECONDARY: BRAND_COLORS.HIGHLIGHT_BLUE,
	BACKGROUND: GREY_SCALE.BACKGROUND_GREY,
} as const
